elev0:
	go run main.go -init="true" -id="0" 

elev1:
	go run main.go -init="true" -id="1" 

elev2:
	go run main.go -init="true" -id="2" 
	
mast:
	clear
	go run main.go -init="true" -id="0" 

sla1: 
	clear
	go run main.go -init="true" -id="1" -elevport="23554" 

sla2: 
	clear
	go run main.go -init="true" -id="2" -elevport="23555" 
